# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_V15KuonWiNzOXRrKxEliozhEWw_6c0
"""

from Deliverable2 import *

# Instantiate the URLValidator class
validator = URLValidator()

# Define multiple queries and URLs
queries_urls = [
    ("Climate change effects", "https://www.nationalgeographic.com/environment/article/climate-change-overview"),
    ("COVID-19 vaccine effectiveness", "https://www.cdc.gov/coronavirus/2019-ncov/vaccines/effectiveness.html"),
    ("Latest AI advancements", "https://www.technologyreview.com/topic/artificial-intelligence"),
    ("Stock market trends", "https://www.bloomberg.com/markets"),
    ("Healthy diet tips", "https://www.healthline.com/nutrition/healthy-eating-tips"),
    ("Space exploration missions", "https://www.nasa.gov/missions"),
    ("Electric vehicle benefits", "https://www.tesla.com/benefits"),
    ("History of the internet", "https://www.history.com/topics/inventions/history-of-the-internet"),
    ("Python programming tutorials", "https://realpython.com"),
    ("Mental health awareness", "https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response")
]

# Run validation for each query and URL
results = [validator.rate_url_validity(query, url) for query, url in queries_urls]

# Print the results
import json
print(json.dumps(results, indent=2))